#!/bin/bash

pulseaudio --start

xrandr --output HDMI-0 --mode 1920x1080 --rate 144 
xrandr --output DP-2 --mode 3840x2160 --scale 0.5x0.5 --rate 60 --right-of HDMI-0

nitrogen --set-zoom-fill --random --head=0 ~/.config/.wallpapers
nitrogen --set-zoom-fill --random --head=1 ~/.config/.wallpapers

xsetroot -cursor_name left_ptr

cd ~

dunst&
picom&
